apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pop-stats-pipeline
description: pop-stats application delivery pipeline
serialPipeline:
 stages:
 - targetId: test

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: test
description: test cluster
anthosCluster:
  membership: projects/kwpark-deloitte-cicd-5afcb309/locations/global/memberships/my-test-cluster
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  workerPool: projects/kwpark-deloitte-cicd-5afcb309/locations/us-central1/workerPools/my-private-pool
  serviceAccount: my-clouddeploy-sa@kwpark-deloitte-cicd-5afcb309.iam.gserviceaccount.com